version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    container_name: dermo_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dermo_clinic
    ports:
      - "5432:5432"
    volumes:
      - dermo_pgdata:/var/lib/postgresql/data

volumes:
  dermo_pgdata:
